### ISSUE TITLE
Wavebar keeps crashing on launch

### ISSUE THREAD

**Issue by greg1075** [hhajime/WaveBar#1]
Wavebar keeps crashing on launch for me. Pasting crash report below:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               WaveBar [40868]
Path:                  /Applications/WaveBar.app/Contents/MacOS/WaveBar
Identifier:            hajime.WaveBar
Version:               1.3.2 (37)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-04-02 17:36:43.4761 -0500
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        5FCA3BEF-173E-F5D6-20C8-4574AF4C969F

Sleep/Wake UUID:       534F7DD6-F6BB-4BB3-BE9E-EF034DFE7973

Time Awake Since Boot: 140000 seconds
Time Since Wake:       1548 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000019b264ee0

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [40868]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x19b264ee0 _assertionFailure(_:_:file:line:flags:) + 268
1   WaveBar                       	       0x1049e15d4 0x1049bc000 + 153044
2   WaveBar                       	       0x1049e0f4c 0x1049bc000 + 151372
3   libdispatch.dylib             	       0x18b3c23e8 _dispatch_client_callout + 20
4   libdispatch.dylib             	       0x18b3c3c68 _dispatch_once_callout + 32
5   WaveBar                       	       0x104a35d80 0x1049bc000 + 499072
6   libdispatch.dylib             	       0x18b3c23e8 _dispatch_client_callout + 20
7   libdispatch.dylib             	       0x18b3c3c68 _dispatch_once_callout + 32
8   WaveBar                       	       0x104a1a8bc 0x1049bc000 + 387260
9   SwiftUI                       	       0x1b73b7f24 0x1b6e2f000 + 5803812
10  WaveBar                       	       0x104a1a528 0x1049bc000 + 386344
11  WaveBar                       	       0x104a1a914 0x1049bc000 + 387348
12  SwiftUI                       	       0x1b87dd4c0 0x1b6e2f000 + 26928320
13  SwiftUI                       	       0x1b85433c0 0x1b6e2f000 + 24200128
14  SwiftUI                       	       0x1b8542ef4 0x1b6e2f000 + 24198900
15  SwiftUI                       	       0x1b6f50570 0x1b6e2f000 + 1185136
16  AttributeGraph                	       0x1b8b0e5c0 AG::Graph::UpdateStack::update() + 512
17  AttributeGraph                	       0x1b8b0edfc AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 424
18  AttributeGraph                	       0x1b8b16e34 AG::Graph::value_ref(AG::AttributeID, unsigned int, AGSwiftMetadata const*, unsigned char&) + 288
19  AttributeGraph                	       0x1b8b2fd1c AGGraphGetValue + 308
20  SwiftUI                       	       0x1b75ee5d0 0x1b6e2f000 + 8123856
21  SwiftUI                       	       0x1b7a57044 0x1b6e2f000 + 12746820
22  SwiftUI                       	       0x1b7a57a14 0x1b6e2f000 + 12749332
23  SwiftUI                       	       0x1b7a57b28 0x1b6e2f000 + 12749608
24  SwiftUI                       	       0x1b78a2244 0x1b6e2f000 + 10957380
25  SwiftUI                       	       0x1b7a57a14 0x1b6e2f000 + 12749332
26  SwiftUI                       	       0x1b87dc828 0x1b6e2f000 + 26925096
27  SwiftUI                       	       0x1b87dcd1c 0x1b6e2f000 + 26926364
28  SwiftUI                       	       0x1b87dc92c 0x1b6e2f000 + 26925356
29  SwiftUI                       	       0x1b8413cd4 0x1b6e2f000 + 22957268
30  SwiftUI                       	       0x1b769e9d4 0x1b6e2f000 + 8845780
31  SwiftUI                       	       0x1b769e8c0 0x1b6e2f000 + 8845504
32  SwiftUI                       	       0x1b7a98a5c 0x1b6e2f000 + 13015644
33  WaveBar                       	       0x104a1a988 0x1049bc000 + 387464
34  dyld                          	       0x18b1ea0e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x18b56dd20 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18b56dd20 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000001   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000600001e4c0c0
    x4: 0x0000600001e4c100   x5: 0x0000000000001b60   x6: 0x00000001f3324888   x7: 0x0000000000000000
    x8: 0x0000000000000080   x9: 0x000000000000007f  x10: 0x0000000000000080  x11: 0x0000000090238001
   x12: 0x00000000000007fb  x13: 0x00000000000007fd  x14: 0x0000000090438802  x15: 0x0000000000000002
   x16: 0x0000000090238001  x17: 0x0000000000038800  x18: 0x0000000000000000  x19: 0x0000000104a63500
   x20: 0x0000600001e4c080  x21: 0x0000000000000000  x22: 0x000000000000000b  x23: 0x000000000000001e
   x24: 0x0000000000000022  x25: 0x0000000104a628a0  x26: 0x300000000000004a  x27: 0x0000000000000000
   x28: 0x000000016b442040   fp: 0x000000016b442000   lr: 0x4a0080019b264ee0
    sp: 0x000000016b441f30   pc: 0x000000019b264ee0 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x104d50000 -        0x104d5bfff libobjc-trampolines.dylib (*) <e8a1b184-0349-3c61-a119-6543eb038317> /usr/lib/libobjc-trampolines.dylib
       0x1049bc000 -        0x104a7bfff hajime.WaveBar (1.3.2) <d08e36cc-a9b9-3ad1-ad27-8cbe48df57c4> /Applications/WaveBar.app/Contents/MacOS/WaveBar
       0x19b22b000 -        0x19b788fff libswiftCore.dylib (*) <05650d36-bbc5-3760-aec7-4d2751b5d729> /usr/lib/swift/libswiftCore.dylib
       0x18b3be000 -        0x18b405fff libdispatch.dylib (*) <7f973554-8168-35bf-ae86-2e9123e81bf7> /usr/lib/system/libdispatch.dylib
       0x1b6e2f000 -        0x1b8b02fff com.apple.SwiftUI (5.4.38.401) <9cf47b50-8046-3dd2-942b-b165c0d98534> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x1b8b03000 -        0x1b8b47fff com.apple.AttributeGraph (5.4.16) <430f8842-b5f8-3668-b43e-cb7c41ed853c> /System/Library/PrivateFrameworks/AttributeGraph.framework/Versions/A/AttributeGraph
       0x18b1e4000 -        0x18b26c9db dyld (*) <f6dd3ec2-85a4-3ab1-8486-b189cd980ebe> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18b56c000 -        0x18b578fff libsystem_pthread.dylib (*) <45239f06-cc53-36d0-9933-7776ac7ea2fa> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=832.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=832.9M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           822.3M       28 
MALLOC guard page                  192K       12 
STACK GUARD                       56.0M        3 
Stack                             9264K        3 
VM_ALLOCATE                         16K        1 
__AUTH                            1529K      280 
__AUTH_CONST                      24.6M      467 
__CTF                               824        1 
__DATA                            10.0M      453 
__DATA_CONST                      22.6M      473 
__DATA_DIRTY                      1391K      155 
__FONT_DATA                          4K        1 
__LINKEDIT                       525.5M        3 
__OBJC_RO                         71.7M        1 
__OBJC_RW                         2195K        1 
__TEXT                           557.2M      489 
dyld private memory                272K        2 
mapped file                       31.3M        4 
shared memory                     1136K        7 
===========                     =======  ======= 
TOTAL                              2.1G     2388 

-----------
Full Report
-----------

{"app_name":"WaveBar","timestamp":"2024-04-02 17:36:43.00 -0500","app_version":"1.3.2","slice_uuid":"d08e36cc-a9b9-3ad1-ad27-8cbe48df57c4","build_version":"37","platform":1,"bundleID":"hajime.WaveBar","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.4.1 (23E224)","roots_installed":0,"name":"WaveBar","incident_id":"15BF0620-DF0C-40B8-9F3F-5A56692C4FA4"}
{
  "uptime" : 140000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "coalitionID" : 15988,
  "osVersion" : {
    "train" : "macOS 14.4.1",
    "build" : "23E224",
    "releaseType" : "User"
  },
  "captureTime" : "2024-04-02 17:36:43.4761 -0500",
  "codeSigningMonitor" : 1,
  "incident" : "15BF0620-DF0C-40B8-9F3F-5A56692C4FA4",
  "pid" : 40868,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-04-02 17:36:43.3854 -0500",
  "procStartAbsTime" : 3427412681176,
  "procExitAbsTime" : 3427414844886,
  "procName" : "WaveBar",
  "procPath" : "\/Applications\/WaveBar.app\/Contents\/MacOS\/WaveBar",
  "bundleInfo" : {"CFBundleShortVersionString":"1.3.2","CFBundleVersion":"37","CFBundleIdentifier":"hajime.WaveBar"},
  "storeInfo" : {"deviceIdentifierForVendor":"49550F77-E4F0-53C0-9A77-9FE20A6C566B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "hajime.WaveBar",
  "crashReporterKey" : "5FCA3BEF-173E-F5D6-20C8-4574AF4C969F",
  "codeSigningID" : "hajime.WaveBar",
  "codeSigningTeamID" : "7C76V3X7AB",
  "codeSigningFlags" : 570520337,
  "codeSigningValidationCategory" : 4,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"4gMZquMDF6rkAxWq5QMTquYDFqrnAxiqFQCA0pYDAJTgAxSqazQPlA==","atPC":"IAAg1CgAgFKJEoBS6BMAuekHAPlIAIBS6AMAOSAnALAA0CeRIycAsA=="},
  "wakeTime" : 1548,
  "sleepWakeUUID" : "534F7DD6-F6BB-4BB3-BE9E-EF034DFE7973",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x000000019b264ee0","rawCodes":[1,6897946336],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":40868},
  "os_fault" : {"process":"WaveBar"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2944327,"threadState":{"x":[{"value":1},{"value":0},{"value":0},{"value":105553148035264},{"value":105553148035328},{"value":7008},{"value":8375126152,"symbolLocation":0,"symbol":"type metadata for _StringBreadcrumbs"},{"value":0},{"value":128},{"value":127},{"value":128},{"value":2418245633},{"value":2043},{"value":2045},{"value":2420344834},{"value":2},{"value":2418245633},{"value":231424},{"value":0},{"value":4372968704},{"value":105553148035200},{"value":0},{"value":11},{"value":30},{"value":34},{"value":4372965536},{"value":3458764513820541002},{"value":0},{"value":6094594112}],"flavor":"ARM_THREAD_STATE64","lr":{"value":5332402703192968928},"cpsr":{"value":1610616832},"fp":{"value":6094594048},"sp":{"value":6094593840},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6897946336,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":237280,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":268,"imageIndex":2},{"imageOffset":153044,"imageIndex":1},{"imageOffset":151372,"imageIndex":1},{"imageOffset":17384,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":3},{"imageOffset":23656,"symbol":"_dispatch_once_callout","symbolLocation":32,"imageIndex":3},{"imageOffset":499072,"imageIndex":1},{"imageOffset":17384,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":3},{"imageOffset":23656,"symbol":"_dispatch_once_callout","symbolLocation":32,"imageIndex":3},{"imageOffset":387260,"imageIndex":1},{"imageOffset":5803812,"imageIndex":4},{"imageOffset":386344,"imageIndex":1},{"imageOffset":387348,"imageIndex":1},{"imageOffset":26928320,"imageIndex":4},{"imageOffset":24200128,"imageIndex":4},{"imageOffset":24198900,"imageIndex":4},{"imageOffset":1185136,"imageIndex":4},{"imageOffset":46528,"symbol":"AG::Graph::UpdateStack::update()","symbolLocation":512,"imageIndex":5},{"imageOffset":48636,"symbol":"AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int)","symbolLocation":424,"imageIndex":5},{"imageOffset":81460,"symbol":"AG::Graph::value_ref(AG::AttributeID, unsigned int, AGSwiftMetadata const*, unsigned char&)","symbolLocation":288,"imageIndex":5},{"imageOffset":183580,"symbol":"AGGraphGetValue","symbolLocation":308,"imageIndex":5},{"imageOffset":8123856,"imageIndex":4},{"imageOffset":12746820,"imageIndex":4},{"imageOffset":12749332,"imageIndex":4},{"imageOffset":12749608,"imageIndex":4},{"imageOffset":10957380,"imageIndex":4},{"imageOffset":12749332,"imageIndex":4},{"imageOffset":26925096,"imageIndex":4},{"imageOffset":26926364,"imageIndex":4},{"imageOffset":26925356,"imageIndex":4},{"imageOffset":22957268,"imageIndex":4},{"imageOffset":8845780,"imageIndex":4},{"imageOffset":8845504,"imageIndex":4},{"imageOffset":13015644,"imageIndex":4},{"imageOffset":387464,"imageIndex":1},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":6}]},{"id":2944334,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6095155200},{"value":6407},{"value":6094618624},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6095155200},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6632693024},"far":{"value":0}}},{"id":2944336,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6095728640},{"value":9987},{"value":6095192064},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6095728640},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6632693024},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4376035328,
    "size" : 49152,
    "uuid" : "e8a1b184-0349-3c61-a119-6543eb038317",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4372283392,
    "CFBundleShortVersionString" : "1.3.2",
    "CFBundleIdentifier" : "hajime.WaveBar",
    "size" : 786432,
    "uuid" : "d08e36cc-a9b9-3ad1-ad27-8cbe48df57c4",
    "path" : "\/Applications\/WaveBar.app\/Contents\/MacOS\/WaveBar",
    "name" : "WaveBar",
    "CFBundleVersion" : "37"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6897709056,
    "size" : 5627904,
    "uuid" : "05650d36-bbc5-3760-aec7-4d2751b5d729",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6630924288,
    "size" : 294912,
    "uuid" : "7f973554-8168-35bf-ae86-2e9123e81bf7",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7363293184,
    "CFBundleShortVersionString" : "5.4.38.401",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 30228480,
    "uuid" : "9cf47b50-8046-3dd2-942b-b165c0d98534",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "5.4.38.401"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7393521664,
    "CFBundleShortVersionString" : "5.4.16",
    "CFBundleIdentifier" : "com.apple.AttributeGraph",
    "size" : 282624,
    "uuid" : "430f8842-b5f8-3668-b43e-cb7c41ed853c",
    "path" : "\/System\/Library\/PrivateFrameworks\/AttributeGraph.framework\/Versions\/A\/AttributeGraph",
    "name" : "AttributeGraph",
    "CFBundleVersion" : "5.4.16"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6628982784,
    "size" : 559580,
    "uuid" : "f6dd3ec2-85a4-3ab1-8486-b189cd980ebe",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6632685568,
    "size" : 53248,
    "uuid" : "45239f06-cc53-36d0-9933-7776ac7ea2fa",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6628229120,
  "size" : 4189880320,
  "uuid" : "a53b7d2f-a773-3524-8828-248b33ef0b4e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=832.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=832.9M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           822.3M       28 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1529K      280 \n__AUTH_CONST                      24.6M      467 \n__CTF                               824        1 \n__DATA                            10.0M      453 \n__DATA_CONST                      22.6M      473 \n__DATA_DIRTY                      1391K      155 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       525.5M        3 \n__OBJC_RO                         71.7M        1 \n__OBJC_RW                         2195K        1 \n__TEXT                           557.2M      489 \ndyld private memory                272K        2 \nmapped file                       31.3M        4 \nshared memory                     1136K        7 \n===========                     =======  ======= \nTOTAL                              2.1G     2388 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "9a38a7b57e71045434c763a13b44a4e0e51d96ff",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62745b8e85854550ad70b6e4",
      "factorPackIds" : {
        "SIRI_TTS_DEVICE_TRAINING" : "6539d7f333b9b7499c6f1b63"
      },
      "deploymentId" : 240000073
    },
    {
      "rolloutId" : "6246d6a916a70b047e454124",
      "factorPackIds" : {

      },
      "deploymentId" : 240000010
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 10151.101.3, proc 8:6:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Jan 20 2024 04:08:41 version 20.103.12.0.8.7.171 FWID 01-e09d2675
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by greg1075** [comment]
Follow up: deleting and reinstalling app fixed the issue.

**Comment by hhajime** [comment]
Hi gerg, thank you so much for full report on this issue, if you have any further assistance, please reach me any time :)
Thanks.

**Comment by hhajime** [comment]
Sorry for the late resolution.
This issue was fixed in version 1.3.3.

Thanks for reporting it!
